### ISSUE TITLE
Streaming a file instead of fully downloading

### ISSUE THREAD

**Issue by evoactivity** [bestmediaplayer/mediaplayer#4]
Do you think it would be possible to use the [streams api](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams) to begin streaming a file without needing to download the full thing before playing?

**Comment by bestmediaplayer** [comment]
hey sry for the delay. I'm not that familiar with the Readable Streams API but I suppose it's possible. If the file was formatted beforehand with ffmpeg segments.

The main way to get this to work is via multiple ffmpeg calls, NOT one main ffmpeg call
